using Microsoft.EntityFrameworkCore.Migrations;

namespace Nesti.Migrations
{
    public partial class AddAutoGeneratedAnnotation : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
